// Minimal Product fixtures for the selector/configurator tests. Hand-built on purpose:
// the tests must pin BEHAVIOUR, not whatever Artisan Bath Co.'s feed happens to contain today
// (data/catalog.normalized.json is regenerated by every ingest, so asserting against it
// would make the suite fail for data reasons rather than code reasons).
import type { Product, ProductVariant, VariantPrice } from "../schema/types";

export interface VariantSpec {
  sku: string | null;
  opts?: Record<string, string>;
  /** customerPrice; null = unpriced (the selector ignores these). */
  price?: number | null;
  available?: boolean;
  image?: string | null;
}

export function makeProduct(o: {
  sku: string | null;
  slug?: string;
  title?: string;
  category?: string;
  variants?: VariantSpec[];
  manualOverride?: number | null;
  attributes?: Record<string, any>;
  primary?: string | null;
}): Product {
  const variants: ProductVariant[] = (o.variants ?? []).map((v) => ({
    sourceSku: v.sku,
    available: v.available !== false,
    sourcePrice: null,
    optionValues: v.opts ?? {},
    image: v.image ?? null,
  }));
  const perVariant: VariantPrice[] = (o.variants ?? []).map((v) => ({
    sku: v.sku,
    basis: "retail",
    itemPrice: null,
    dealerPrice: null,
    retailPrice: null,
    customerPrice: v.price === undefined ? 1000 : v.price,
  }));
  const priced = perVariant.map((p) => p.customerPrice).filter((n): n is number => n != null);
  return {
    source: { platform: "shopify", partner: "Artisan Bath Co.", id: o.sku ?? "x", handle: o.slug ?? "s" },
    partner: "Artisan Bath Co.",
    category: o.category ?? "Vanities",
    title: o.title ?? (o.sku ?? "Product"),
    slug: o.slug ?? String(o.sku ?? "s").toLowerCase(),
    sourceSku: o.sku,
    descriptionHtml: "",
    descriptionText: "",
    tags: [],
    images: { primary: o.primary ?? "https://blob/p.webp", gallery: ["https://blob/p.webp"], sourceCount: 1 },
    attributes: o.attributes ?? {},
    variants,
    pricing: {
      model: "formula_v1",
      formula: { taxRate: 0.07, multiplier: 4, expression: "x" },
      basis: "retail",
      perVariant,
      startingAt: priced.length ? Math.min(...priced) : null,
      priceRange: priced.length ? { low: Math.min(...priced), high: Math.max(...priced) } : null,
      manualOverride: o.manualOverride ?? null,
    },
    status: "published",
  };
}

/** Convenience: a family of per-size sibling products (the the supplier cross-link model). */
export function family(skus: string[]): Product[] {
  return skus.map((sku) => makeProduct({ sku, slug: sku.toLowerCase(), variants: [{ sku, price: 1000 }] }));
}
